# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c1a217629b403567c4a072bf5b77c2f806a1700bb863d4c503965dbe1a51219b9d61b05ec567198c354da39aaa482ce6ccb0a77f8945dbcb47f92f265e9a447

test:
  secret_key_base: 83686448a02f0cf3817079b9cd8a6cbd6d88d75bfd1ed8e96542a69380550c9cae44d8da07832c14dfaf9afa5bf716f7d597cda4864740e26cce21a2168660eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
